name: St. Ranger
favicon: null
layout_spectrum: 0.73828
typography_spectrum: 0.15799
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#2c3053'
    - '#c8a798'
    - '#47546c'
    - '#8b6871'
  brandStrength: 0.125
  lightness: 0.6875
  saturation: 0.4222426898777485
  rhythmicContrast: 0.5
purpose: []
