purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.5179211
  brandStrength: 0.5985663
  lightness: 0.9928315
  brandColors:
    - '#ffffff'
    - '#2c3053'
    - '#c8a798'
    - '#47546c'
    - '#8b6871'
  rhythmicContrast: 0.6935484
cta:
  bucket: null
  version: null
  domain: null
favicon: null
name: St. Ranger
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.15799
layout_spectrum: 0.5806451
